# Generated by Django 4.1.3 on 2024-02-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="chat_id",
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="poll",
            name="poll_question",
            field=models.TextField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="poll",
            name="thread_name",
            field=models.TextField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="telegram_id",
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
    ]
