# Generated by Django 4.1.3 on 2024-01-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='reference_id',
            field=models.TextField(db_index=True, default='', max_length=128),
        ),
    ]
