# Generated by Django 4.1.3 on 2024-02-21 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_training_reference_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thread_id", models.IntegerField(db_index=True, default=0)),
                (
                    "thread_name",
                    models.TextField(db_index=True, default="", max_length=128),
                ),
                (
                    "poll_id",
                    models.TextField(db_index=True, default="", max_length=128),
                ),
                (
                    "poll_header",
                    models.TextField(db_index=True, default="", max_length=128),
                ),
                ("chat_id", models.IntegerField(db_index=True, default=0)),
                ("message_id", models.IntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="training",
            name="reference_id",
        ),
        migrations.AddField(
            model_name="training",
            name="max_people",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="PollVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                (
                    "voted_option",
                    models.TextField(db_index=True, default="", max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bot.poll"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="training",
            name="poll",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="bot.poll"
            ),
        ),
    ]
