# Generated by Django 4.1.3 on 2024-02-07 16:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_training_reference_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.TextField(db_index=True, default='', max_length=128)),
                ('thread_name', models.TextField(db_index=True, default='', max_length=128)),
                ('poll_header', models.TextField(db_index=True, default='', max_length=128)),
                ('message_id', models.TextField(db_index=True, default='', max_length=128)),
                ('chat_id', models.TextField(db_index=True, default='', max_length=128)),
                ('thread_id', models.TextField(db_index=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='training',
            name='chat_id',
            field=models.TextField(db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='training',
            name='message_id',
            field=models.TextField(db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='training',
            name='poll_header',
            field=models.TextField(db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='training',
            name='thread_id',
            field=models.TextField(db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='training',
            name='thread_name',
            field=models.TextField(db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='training',
            name='reference_id',
            field=models.TextField(db_index=True, default=uuid.UUID('aa159dd4-c5d6-11ee-b18e-2a8610ce7e84'), max_length=128),
        ),
    ]
