# Generated by Django 4.1.3 on 2024-02-29 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_alter_poll_chat_id_alter_poll_poll_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pollvote",
            name="telegram_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bot.telegramuser",
            ),
        ),
    ]
