# Generated by Django 4.1.3 on 2024-02-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_alter_pollvote_telegram_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="when",
            field=models.TextField(default="", max_length=512),
        ),
    ]
