# Generated by Django 4.1.3 on 2024-02-21 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_poll_remove_training_reference_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="poll",
            old_name="poll_header",
            new_name="poll_question",
        ),
    ]
