# Generated by Django 4.1.3 on 2024-02-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0004_rename_poll_header_poll_poll_question"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pollvote",
            old_name="voted_option",
            new_name="option",
        ),
        migrations.AlterField(
            model_name="pollvote",
            name="user_id",
            field=models.IntegerField(db_index=True),
        ),
    ]
