# Generated by Django 4.1.3 on 2024-02-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0005_rename_voted_option_pollvote_option_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="message_id",
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="poll",
            name="poll_id",
            field=models.TextField(db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="poll",
            name="thread_id",
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
