# Generated by Django 4.1.3 on 2024-02-21 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0006_alter_poll_message_id_alter_poll_poll_id_and_more"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="pollvote",
            index_together={("user_id", "poll")},
        ),
    ]
