# Generated by Django 4.1.3 on 2024-03-14 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0006_remove_training_when_training_day"),
    ]

    operations = [
        migrations.RenameField(
            model_name="training",
            old_name="day",
            new_name="date",
        ),
    ]
