# Generated by Django 4.1.3 on 2024-03-15 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0007_rename_day_training_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollvote",
            name="vote_source",
            field=models.CharField(
                choices=[("PLUS_ONE_COMMAND", "+1"), ("POLL", "Poll Vote")],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pollvote",
            name="go",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="first_name",
            field=models.CharField(db_index=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="last_name",
            field=models.CharField(db_index=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="username",
            field=models.CharField(db_index=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="training",
            name="poll",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="training",
                to="bot.poll",
            ),
        ),
    ]
