# Generated by Django 4.1.3 on 2024-03-15 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0008_pollvote_vote_source_alter_pollvote_go_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PollVote",
            new_name="Attendee",
        ),
    ]
