# Generated by Django 4.1.3 on 2024-03-15 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0009_rename_pollvote_attendee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendee",
            name="poll",
        ),
        migrations.AddField(
            model_name="attendee",
            name="training",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendees",
                to="bot.training",
            ),
        ),
    ]
