# Generated by Django 4.1.3 on 2024-03-15 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0012_alter_attendee_source_alter_attendee_training"),
    ]

    operations = [
        migrations.RenameField(
            model_name="training",
            old_name="max_people",
            new_name="attendees_limit",
        ),
    ]
