# Generated by Django 4.1.3 on 2024-03-19 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0013_rename_max_people_training_attendees_limit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="training",
            name="poll",
        ),
        migrations.AddField(
            model_name="poll",
            name="training",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="poll",
                to="bot.training",
            ),
        ),
    ]
