# Generated by Django 4.1.3 on 2024-03-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0014_remove_training_poll_poll_training"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_flag",
                    models.CharField(
                        choices=[("PLUS_ONE_COMMAND", "Disable +1")],
                        max_length=128,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
