# Generated by Django 4.1.3 on 2024-03-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0015_featureflag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureflag",
            name="feature_flag",
            field=models.CharField(
                choices=[("DISABLE_PLUS_ONE_COMMAND", "Disable +1")],
                db_index=True,
                max_length=128,
                unique=True,
            ),
        ),
    ]
